version: "3.9"

services:
  screenshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: screenshare_all_in_one
    restart: unless-stopped
    environment:
      DB_HOST: evo-pg
      DB_PORT: 5432
      DB_NAME: screenshare_db
      DB_USER: screenshare_user
      DB_PASSWORD: ScreenShare2025!
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8890:8890"
      - "8189:8189/udp"
      - "9997:9997"
    networks:
      - evolution-net
    external_links:
      - evo-pg

networks:
  evolution-net:
    external: true
